# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dev',
            options={'ordering': ['url']},
        ),
        migrations.AlterModelOptions(
            name='hosts',
            options={'ordering': ['ip']},
        ),
        migrations.AlterModelOptions(
            name='pro',
            options={'ordering': ['url']},
        ),
    ]
