# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0002_auto_20190628_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='\u7c7b\u522b')),
            ],
        ),
    ]
