# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='navi.category', verbose_name='\u7c7b\u522b'),
        ),
    ]
