# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0004_pro_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('description', models.CharField(max_length=50, verbose_name='\u63cf\u8ff0')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=10, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='navi.category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
