# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8d1f\u8d23\u4eba\u59d3\u540d')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='\u8d1f\u8d23\u4eba\u624b\u673a')),
                ('qq', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4ebaQQ')),
                ('dingding', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4eba\u9489\u9489')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4eba\u90ae\u7bb1')),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u6570\u636e\u5e93\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u63cf\u8ff0')),
                ('ops', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.AppOwner', verbose_name='\u8fd0\u7ef4\u8d1f\u8d23\u4eba')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u4ea7\u54c1\u7ebf\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ea7\u54c1\u7ebf\u63cf\u8ff0')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.AppOwner', verbose_name='\u4ea7\u54c1\u7ebf\u8d1f\u8d23\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e94\u7528\u63cf\u8ff0')),
                ('current_ver', models.CharField(blank=True, default='0.0.0', max_length=255, verbose_name='\u5f53\u524d\u7248\u672c')),
                ('language_type', models.CharField(choices=[('Java', 'Java'), ('PHP', 'PHP'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('C/C++', 'C/C++'), ('Go', 'Go'), ('Other', 'Other')], max_length=30, null=True, verbose_name='\u8bed\u8a00\u7c7b\u578b')),
                ('app_type', models.CharField(choices=[('\u5b9a\u65f6', '\u5b9a\u65f6'), ('\u5e38\u9a7b', '\u5e38\u9a7b')], max_length=30, null=True, verbose_name='\u7a0b\u5e8f\u7c7b\u578b')),
                ('app_arch', models.CharField(blank=True, choices=[('Spring Boot 1.x', 'Spring Boot 1.x'), ('Spring Boot 2.x', 'Spring Boot 2.x'), ('Spark Steaming', 'Spark Steaming'), ('Laravel', 'Laravel'), ('Yii 2.x', 'Yii 2.x'), ('WordPress', 'WordPress'), ('Vue.js', 'Vue.js'), ('Scrapy', 'Scrapy'), ('Other', 'Other')], max_length=30, null=True, verbose_name='\u7a0b\u5e8f\u6846\u67b6')),
                ('code_address', models.CharField(max_length=255, null=True, verbose_name='\u4ee3\u7801\u5e93\u5730\u5740')),
                ('start_cmd', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u542f\u52a8\u547d\u4ee4')),
                ('stop_cmd', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u505c\u6b62\u547d\u4ee4')),
                ('config_detail', models.TextField(blank=True, max_length=5000, null=True, verbose_name='\u914d\u7f6e\u6587\u4ef6\u8bf4\u660e')),
                ('docker_expose', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Docker\u5bb9\u5668\u8bf4\u660e')),
                ('app_monitor', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9700\u8981\u7684\u4e1a\u52a1\u76d1\u63a7\u9879')),
                ('need_ha', models.CharField(choices=[('\u7a0b\u5e8f\u539f\u751f\u652f\u6301\u9ad8\u53ef\u7528', '\u7a0b\u5e8f\u539f\u751f\u652f\u6301\u9ad8\u53ef\u7528'), ('\u65e0\u9700\u9ad8\u53ef\u7528', '\u65e0\u9700\u9ad8\u53ef\u7528'), ('\u9700\u8981\u989d\u5916\u914d\u7f6e\u9ad8\u53ef\u7528', '\u9700\u8981\u989d\u5916\u914d\u7f6e\u9ad8\u53ef\u7528')], default='\u65e0\u9700\u9ad8\u53ef\u7528', max_length=30, verbose_name='\u9ad8\u53ef\u7528\u8bf4\u660e')),
                ('need_dn', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9700\u8981\u65b0\u589e\u57df\u540d')),
                ('need_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9700\u8981\u65b0\u589e\u4e8c\u7ea7\u76ee\u5f55')),
                ('uri_mapping_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='URI\u6620\u5c04\u6765\u6e90')),
                ('uri_mapping_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='URI\u6620\u5c04\u76ee\u6807')),
                ('need_wan', models.CharField(choices=[('\u662f', '\u662f'), ('\u5426', '\u5426')], default='\u5426', max_length=2, verbose_name='\u662f\u5426\u9700\u8981\u8bbf\u95ee\u5916\u7f51')),
                ('requester', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8c03\u7528\u65b9')),
                ('rely_on', models.TextField(blank=True, max_length=255, null=True, verbose_name='\u5e94\u7528\u4f9d\u8d56\u7684\u5176\u4ed6\u9700\u6c42')),
                ('dev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev', to='appconf.AppOwner', verbose_name='\u5f00\u53d1\u8d1f\u8d23\u4eba')),
                ('ops', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops', to='appconf.AppOwner', verbose_name='\u8fd0\u7ef4\u8d1f\u8d23\u4eba')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Product', verbose_name='\u6240\u5c5e\u4ea7\u54c1\u7ebf')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='database',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Product', verbose_name='\u6240\u5c5e\u4ea7\u54c1\u7ebf'),
        ),
    ]
