# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 02:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='codename',
            field=models.CharField(max_length=50, null=True, verbose_name='\u4ea7\u54c1\u7ebf\u4ee3\u53f7'),
        ),
        migrations.AlterField(
            model_name='appowner',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_arch',
            field=models.CharField(blank=True, choices=[('Spring Boot 1.x', 'Spring Boot 1.x'), ('Spring Boot 2.x', 'Spring Boot 2.x'), ('Spark', 'Spark'), ('Spark Steaming', 'Spark Steaming'), ('Laravel', 'Laravel'), ('Yii 2.x', 'Yii 2.x'), ('WordPress', 'WordPress'), ('Vue.js', 'Vue.js'), ('Scrapy', 'Scrapy'), ('Other', 'Other')], max_length=30, null=True, verbose_name='\u7a0b\u5e8f\u6846\u67b6'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language_type',
            field=models.CharField(choices=[('Java', 'Java'), ('Scala', 'Scala'), ('PHP', 'PHP'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('C/C++', 'C/C++'), ('Go', 'Go'), ('Other', 'Other')], max_length=30, null=True, verbose_name='\u8bed\u8a00\u7c7b\u578b'),
        ),
    ]
