# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0002_auto_20190628_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_offline',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0b\u67b6'),
        ),
        migrations.AlterField(
            model_name='project',
            name='app_type',
            field=models.CharField(choices=[('\u5b9a\u65f6', '\u5b9a\u65f6'), ('\u5e38\u9a7b', '\u5e38\u9a7b'), ('\u5ba2\u6237\u7aef', '\u5ba2\u6237\u7aef')], max_length=30, null=True, verbose_name='\u7a0b\u5e8f\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language_type',
            field=models.CharField(choices=[('Java', 'Java'), ('Scala', 'Scala'), ('PHP', 'PHP'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('C/C++', 'C/C++'), ('Go', 'Go'), ('Objective-C', 'Objective-C'), ('Other', 'Other')], max_length=30, null=True, verbose_name='\u8bed\u8a00\u7c7b\u578b'),
        ),
    ]
