# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0003_auto_20200420_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_arch',
            field=models.CharField(blank=True, choices=[('Spring Boot 1.x', 'Spring Boot 1.x'), ('Spring Boot 2.x', 'Spring Boot 2.x'), ('Spark', 'Spark'), ('Spark Steaming', 'Spark Steaming'), ('Laravel', 'Laravel'), ('Yii 2.x', 'Yii 2.x'), ('WordPress', 'WordPress'), ('Vue.js', 'Vue.js'), ('Scrapy', 'Scrapy'), ('Go-Kit', 'Go-Kit'), ('Kratos', 'Kratos'), ('Other', 'Other')], max_length=30, null=True, verbose_name='\u7a0b\u5e8f\u6846\u67b6'),
        ),
    ]
