# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0004_auto_20200513_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa', to='appconf.AppOwner', verbose_name='\u6d4b\u8bd5\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='appconf.AppOwner', verbose_name='\u4ea7\u54c1\u7ebf\u8d1f\u8d23\u4eba'),
        ),
    ]
