# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-01 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0005_auto_20200601_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
