# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-02-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='ip_range',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='jigui',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='tel',
        ),
        migrations.AddField(
            model_name='idc',
            name='intranet',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u670d\u52a1\u5668\u5185\u7f51IP'),
        ),
        migrations.AddField(
            model_name='idc',
            name='network',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u670d\u52a1\u5668\u5916\u7f51IP'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='ids',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u670d\u52a1\u5668\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u670d\u52a1\u5668\u540d\u79f0'),
        ),
    ]
