# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_from', models.CharField(max_length=50, null=True, verbose_name='\u59d4\u6d3e\u4eba')),
                ('delegater_dingding', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u59d4\u6d3e\u4eba\u9489\u9489')),
                ('delegate_to', models.CharField(max_length=50, null=True, verbose_name='\u88ab\u59d4\u6d3e\u4eba')),
            ],
        ),
    ]
