# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-31 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delegatelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatelist',
            name='delegate_to',
            field=models.CharField(max_length=50, null=True, verbose_name='\u63a5\u53d7\u59d4\u6d3e'),
        ),
        migrations.AlterUniqueTogether(
            name='delegatelist',
            unique_together=set([('delegate_from', 'delegate_to')]),
        ),
    ]
