# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-31 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191231_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delegatelist',
            unique_together=set([('delegate_from',)]),
        ),
    ]
