# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191231_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegatelist',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u4eba'),
        ),
    ]
