# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-01 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delegatelist_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegatelist',
            options={'ordering': ['starttime']},
        ),
        migrations.AddField(
            model_name='delegatelist',
            name='delegate_status',
            field=models.BooleanField(default=False, verbose_name='\u59d4\u6d3e\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='delegatelist',
            name='endtime',
            field=models.DateTimeField(null=True, verbose_name='\u59d4\u6d3e\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='delegatelist',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='\u59d4\u6d3e\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
