# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-01 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200101_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegatelist',
            name='delegate_status',
            field=models.IntegerField(default=0, verbose_name='\u59d4\u6d3e\u72b6\u6001'),
        ),
    ]
