# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200108_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delegatelist',
            unique_together=set([]),
        ),
    ]
