# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200108_1022'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='delegatelist',
            index_together=set([('delegate_from_id', 'delegate_to_id')]),
        ),
    ]
