# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-13 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200108_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['username']},
        ),
    ]
