# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appconf', '0004_auto_20200513_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u662f\u5426\u540c\u6b65')),
                ('test_ver', models.CharField(blank=True, default='0.0.0', max_length=255, verbose_name='\u6d4b\u8bd5\u7248\u672c')),
                ('pid', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ansible\u9879\u76ee\u53f7')),
                ('tid', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ansible\u6a21\u677f\u53f7')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Project', verbose_name='\u5e94\u7528\u540d\u79f0')),
            ],
        ),
    ]
