# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0004_auto_20200513_1704'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(null=True, verbose_name='\u59d4\u6d3e\u5f00\u59cb\u65f6\u95f4')),
                ('endtime', models.DateTimeField(null=True, verbose_name='\u59d4\u6d3e\u7ed3\u675f\u65f6\u95f4')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Product', verbose_name='\u4ea7\u54c1\u7ebf\u540d\u79f0')),
            ],
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['project']},
        ),
    ]
