# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20200518_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersyncDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(null=True, verbose_name='\u4efb\u52a1\u5f00\u59cb\u65f6\u95f4')),
                ('endtime', models.DateTimeField(null=True, verbose_name='\u4efb\u52a1\u7ed3\u675f\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='versync',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='versync',
            name='submittime',
            field=models.DateTimeField(null=True, verbose_name='\u4efb\u52a1\u63d0\u4ea4\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='versync',
            name='sync_status',
            field=models.IntegerField(null=True, verbose_name='\u4efb\u52a1\u6267\u884c\u72b6\u6001\uff0c0\uff1a\u63d0\u4ea4\uff0c1\uff1a\u6267\u884c\u4e2d\uff0c2\uff1a\u6210\u529f\uff0c3\uff1a\u5931\u8d25'),
        ),
        migrations.AlterField(
            model_name='versync',
            name='endtime',
            field=models.DateTimeField(null=True, verbose_name='\u4efb\u52a1\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='versync',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='\u4efb\u52a1\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='versyncdetail',
            name='Versync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.Versync', verbose_name='\u540c\u6b65\u4efb\u52a1\u53f7'),
        ),
    ]
