# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-22 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200521_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='versync',
            name='progress',
            field=models.IntegerField(null=True, verbose_name='\u4efb\u52a1\u8fdb\u5ea6'),
        ),
    ]
