# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0004_auto_20200513_1704'),
        ('tests', '0004_versync_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='versyncdetail',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Project', verbose_name='\u5e94\u7528\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='versyncdetail',
            name='sync_status',
            field=models.IntegerField(null=True, verbose_name='\u4efb\u52a1\u6267\u884c\u72b6\u6001\uff0c0\uff1a\u63d0\u4ea4\uff0c1\uff1a\u6267\u884c\u4e2d\uff0c2\uff1a\u6210\u529f\uff0c3\uff1a\u5931\u8d25'),
        ),
        migrations.AlterField(
            model_name='versync',
            name='progress',
            field=models.IntegerField(default=0, null=True, verbose_name='\u4efb\u52a1\u8fdb\u5ea6'),
        ),
    ]
