# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-25 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20200525_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versyncdetail',
            old_name='Project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='versyncdetail',
            old_name='Versync',
            new_name='versync',
        ),
    ]
