# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-26 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20200525_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versyncdetail',
            old_name='sync_status',
            new_name='task_status',
        ),
    ]
