# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-26 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_auto_20200526_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='versyncdetail',
            name='sync_version',
            field=models.CharField(blank=True, default='0.0.0', max_length=255, verbose_name='\u540c\u6b65\u7248\u672c'),
        ),
    ]
