# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_versyncdetail_sync_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='versyncdetail',
            name='task_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ansible\u4efb\u52a1\u53f7'),
        ),
    ]
