# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0004_auto_20200513_1704'),
        ('tests', '0009_versyncdetail_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u9700\u6c42\u521b\u5efa\u65f6\u95f4')),
                ('finishtime', models.DateTimeField(null=True, verbose_name='\u6d4b\u8bd5\u5b8c\u6210\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('order_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63d0\u4ea4\u7528\u6237')),
                ('status', models.BooleanField(default=False, verbose_name='\u9700\u6c42\u72b6\u6001')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Product', verbose_name='\u4ea7\u54c1\u7ebf\u540d\u79f0')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='versync',
            name='sync_status',
            field=models.IntegerField(null=True, verbose_name='\u4efb\u52a1\u6267\u884c\u72b6\u6001\uff0c0\uff1a\u63d0\u4ea4\uff0c1\uff1a\u6267\u884c\u4e2d\uff0c2\uff1a\u540c\u6b65Nginx\uff0c3\uff1a\u6210\u529f\uff0c4\uff1a\u5931\u8d25'),
        ),
    ]
