# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-27 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20200527_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u66f4\u65b0\u63cf\u8ff0'),
        ),
    ]
