# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20200529_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='feedback',
            field=models.IntegerField(default=0, null=True, verbose_name='\u6d4b\u8bd5\u53cd\u9988\uff0c0\uff1a\u672a\u53cd\u9988\uff0c1\uff1a\u540c\u610f\u4e0a\u7ebf\uff0c2\uff1a\u62d2\u7edd\u4e0a\u7ebf'),
        ),
    ]
