# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-02 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_apply_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='description',
            field=models.CharField(max_length=5000, null=True, verbose_name='\u9700\u6c42\u63cf\u8ff0'),
        ),
    ]
