# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20200603_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='test_ver',
            field=models.CharField(blank=True, default='0.0.0', max_length=255, verbose_name='\u6d4b\u8bd5\u7248\u672c'),
        ),
    ]
