# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20200603_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='tid',
        ),
        migrations.AddField(
            model_name='environment',
            name='app_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u5e94\u7528\u7c7b\u578b\uff0c0\uff1adocker\uff0c1\uff1aother'),
        ),
        migrations.AddField(
            model_name='environment',
            name='endtime',
            field=models.DateTimeField(null=True, verbose_name='\u4efb\u52a1\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='environment',
            name='pre_pid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='PreAnsible\u9879\u76ee\u53f7'),
        ),
        migrations.AddField(
            model_name='environment',
            name='pre_tid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='PreAnsible\u6a21\u677f\u53f7'),
        ),
        migrations.AddField(
            model_name='environment',
            name='pre_ver',
            field=models.CharField(blank=True, default='0.0.0', max_length=255, verbose_name='\u9884\u53d1\u5e03\u7248\u672c'),
        ),
        migrations.AddField(
            model_name='environment',
            name='task_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ansible\u4efb\u52a1\u53f7'),
        ),
        migrations.AddField(
            model_name='environment',
            name='task_status',
            field=models.IntegerField(null=True, verbose_name='\u4efb\u52a1\u6267\u884c\u72b6\u6001\uff0c0\uff1a\u63d0\u4ea4\uff0c1\uff1a\u6267\u884c\u4e2d\uff0c2\uff1a\u6210\u529f\uff0c3\uff1a\u5931\u8d25'),
        ),
        migrations.AddField(
            model_name='environment',
            name='test_pid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='TestAnsible\u9879\u76ee\u53f7'),
        ),
        migrations.AddField(
            model_name='environment',
            name='test_tid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='TestAnsible\u6a21\u677f\u53f7'),
        ),
    ]
