# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbscript',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u66f4\u65b0\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u66f4\u65b0\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u5e94\u7528\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='require',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='\u9700\u6c42\u63cf\u8ff0'),
        ),
    ]
