# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190522_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='\u66f4\u65b0\u63cf\u8ff0'),
        ),
    ]
