# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-25 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_dbscript_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbscript',
            name='env',
            field=models.CharField(choices=[('Pre', '\u9884\u53d1\u5e03\u73af\u5883'), ('Pro', '\u751f\u4ea7\u73af\u5883')], max_length=10, null=True, verbose_name='\u73af\u5883'),
        ),
    ]
