# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191225_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbscript',
            name='env',
            field=models.CharField(max_length=10, null=True, verbose_name='\u73af\u5883'),
        ),
    ]
