# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-16 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191231_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u65b0\u5e94\u7528'),
        ),
    ]
