# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deploy_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='is_tested',
            field=models.IntegerField(default=0, null=True, verbose_name='\u662f\u5426\u6d4b\u8bd5\u901a\u8fc7\uff0c0\uff1a\u672a\u786e\u5b9a\uff0c1\uff1a\u6d4b\u8bd5\u901a\u8fc7\uff0c2\uff1a\u6d4b\u8bd5\u672a\u901a\u8fc7'),
        ),
    ]
