# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_deploy_is_tested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbscript',
            options={'ordering': ['-completion_time', 'operating_time']},
        ),
        migrations.AlterModelOptions(
            name='deploy',
            options={'ordering': ['-completion_time', 'operating_time']},
        ),
        migrations.AlterModelOptions(
            name='require',
            options={'ordering': ['-completion_time', 'operating_time']},
        ),
        migrations.AddField(
            model_name='dbscript',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='require',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4'),
        ),
    ]
