# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-02 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0006_auto_20200601_1218'),
        ('orders', '0010_auto_20200729_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=255, null=True, verbose_name='\u73af\u5883')),
                ('description', models.CharField(max_length=5000, null=True, verbose_name='\u66f4\u65b0\u63cf\u8ff0')),
                ('conf_version', models.CharField(max_length=255, unique=True, verbose_name='\u914d\u7f6e\u7248\u672c\u53f7')),
                ('status', models.BooleanField(default=False, verbose_name='\u90e8\u7f72\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('operating_time', models.DateTimeField(null=True, verbose_name='\u9884\u7ea6\u64cd\u4f5c\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('order_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63d0\u4ea4\u7528\u6237')),
                ('order_status', models.BooleanField(default=False, verbose_name='\u5de5\u5355\u72b6\u6001')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('app_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Project', verbose_name='\u5e94\u7528\u540d\u79f0')),
            ],
            options={
                'ordering': ['-completion_time', 'operating_time'],
            },
        ),
        migrations.AlterField(
            model_name='deploy',
            name='version',
            field=models.CharField(max_length=255, unique=True, verbose_name='\u7a0b\u5e8f\u7248\u672c\u53f7'),
        ),
        migrations.AddField(
            model_name='config',
            name='app_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Deploy', to_field='version', verbose_name='\u7a0b\u5e8f\u7248\u672c\u53f7'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='conf_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Config', to_field='conf_version', verbose_name='\u914d\u7f6e\u7248\u672c\u53f7'),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set([('app_name', 'conf_version', 'app_version')]),
        ),
    ]
